website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^whayp/', include('whayp.urls')),
    url(r'^', include('whayp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whayp/urls.py
from django.conf.urls import url

from . import views

app_name = 'whayp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<photo_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^photos/(?P<filter_by>[a-zA_Z]+)/$', views.photos, name='photos'),
    url(r'^create_post/$', views.create_post, name='create_post'),
    url(r'^(?P<post_id>[0-9]+)/favorite_post/$', views.favorite_post, name='favorite_post'),
    url(r'^(?P<post_id>[0-9]+)/delete_post/$', views.delete_post, name='delete_post'),
]

whayp/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    user = models.ForeignKey(User, default=1)
    description = models.CharField(max_length=250, default='')
    pub_date = models.DateTimeField(default=datetime.now())
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + ' - ' + self.description


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    photo_file = models.FileField()
    is_favorite = models.BooleanField(default=False)
    is_main = models.BooleanField(default=False)

whayp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from .models import Post, Photo
from django.forms import formset_factory

MAX_PHOTOS = 10


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['description']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

whayp/views.py
import uuid

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from .forms import PostForm, UserForm
from .models import Post, Photo

EXT = '.jpg'

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_post(request):
    if not request.user.is_authenticated():
        return render(request, 'whayp/login.html')
    else:
        form = PostForm(request.POST)
        if request.POST:
            post = form.save(commit=False)
            file_list = request.FILES.getlist("myfiles")
            if form.is_valid():
                for tmp in filter(lambda w: w.name.split('.')[-1] not in IMAGE_FILE_TYPES, file_list):
                    return render(request, 'whayp/create_post.html', {
                        'post': post,
                        'form': form,
                        'error_message': 'Image file must be PNG, JPG, or JPEG',
                    })
                post.user = request.user
                post.save()
                for count, file in enumerate(file_list):
                    file_name = str(uuid.uuid4())
                    photo = Photo()
                    photo.post = post
                    file.name = file_name + EXT
                    photo.photo_file = file
                    photo.save()
                return render(request, 'whayp/detail.html', {'post': post})
            else:
                return render(request, 'whayp/create_post.html', {
                    "form": form,
                    'error_message': 'Add image, please',
                })
        return render(request, 'whayp/create_post.html', {
            "form": form,
        })


def process(file, file_path):
    with open(file_path, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)


def delete_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.delete()
    posts = Post.objects.filter(user=request.user)
    return render(request, 'whayp/index.html', {'posts': posts})


def detail(request, post_id):
    if not request.user.is_authenticated():
        return render(request, 'whayp/login.html')
    else:
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        return render(request, 'whayp/detail.html', {'post': post, 'user': user})


def favorite(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    try:
        photo.is_favorite = not photo.is_favorite
        photo.save()
    except (KeyError, Photo.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        post.is_favorite = not post.is_favorite
        for ph in post.photo_set.all():
            ph.is_favorite = True
            ph.save()
        post.save()
    except (KeyError, Post.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'whayp/login.html')
    else:
        posts = Post.objects.filter(user=request.user)
        photo_results = Photo.objects.all()
        query = request.GET.get("q")
        if query:
            posts = posts.filter(
                Q(post_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()
            photo_results = photo_results.filter(
                Q(photo_title__icontains=query)
            ).distinct()
            return render(request, 'whayp/index.html', {
                'posts': posts,
                'photos': photo_results,
            })
        else:
            return render(request, 'whayp/index.html', {'posts': posts})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'whayp/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                posts = Post.objects.filter(user=request.user)
                return render(request, 'whayp/index.html', {'posts': posts})
            else:
                return render(request, 'whayp/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'whayp/login.html', {'error_message': 'Invalid login'})
    return render(request, 'whayp/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                posts = Post.objects.filter(user=request.user)
                return render(request, 'whayp/index.html', {'posts': posts})
    context = {
        "form": form,
    }
    return render(request, 'whayp/register.html', context)


def photos(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'whayp/login.html')
    else:
        try:
            photo_ids = []
            for post in Post.objects.filter(user=request.user):
                for photo in post.photo_set.all():
                    photo_ids.append(photo.pk)
            users_photos = Photo.objects.filter(pk__in=photo_ids)
            if filter_by == 'favorites':
                users_photos = users_photos.filter(is_favorite=True)
        except Post.DoesNotExist:
            users_photos = []
        return render(request, 'whayp/photos.html', {
            'photo_list': users_photos,
            'filter_by': filter_by,
        })

whayp/templates/whayp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Whayp{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'whayp/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'whayp/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'whayp:index' %}">whayp</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block posts_active %}{% endblock %}"><a href="{% url 'whayp:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Posts</a></li>
                <li class="{% block photos_active %}{% endblock %}"><a href="{% url 'whayp:photos' 'all' %}"><span class="glyphicon glyphicon-whayp" aria-hidden="true"></span>&nbsp; Photos</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'whayp:create_post' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Post
                    </a>
                </li>
                <li>
                    <a href="{% url 'whayp:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

whayp/templates/whayp/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Whayp{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'whayp/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'whayp/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'whayp:index' %}">whayp</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'whayp:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'whayp:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

whayp/templates/whayp/create_post.html
{% extends 'whayp/base.html' %}
{% block title %}Add a New Post{% endblock %}
{% block posts_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Post</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                          {{ form.as_table }}
                           <input type="file" name="myfiles" multiple>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is whayp?</h3>
                    <p>App description.</p>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

whayp/templates/whayp/detail.html
{% extends 'whayp/base.html' %}
{% block posts_active %}active{% endblock %}

{% block body %}
<div class="container-fluid photos-container">

    <div class="row">
        <!-- Right Photo Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">

                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% for photo in post.photo_set.all %}
                                <img src="{{photo.photo_file.url}}"  style="width:300px;height:200px;">
                    {% endfor %}
                    </table>

                </div>
            </div>

        </div>
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>{{user}}</h2>
                    {{post.description}}
                    <BR>
                    {{post.pub_date}}
                      <a href="{% url 'whayp:favorite_post' post.id %}" class="btn btn-default btn-sm btn-favorite"
                           role="button">
                            <span class="glyphicon glyphicon-star {% if post.is_favorite %}active{% endif %}"></span>
                        </a>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

whayp/templates/whayp/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

whayp/templates/whayp/index.html
{% extends 'whayp/base.html' %}
{% block posts_active %}active{% endblock %}

{% block body %}
<div class="posts-container container-fluid">

    <!-- Post
   s -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Posts</h3>
        </div>
        {% if posts %}
        {% for post in posts %}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href="{% url 'whayp:detail' post.id %}">
                    <h2>{{ post.description }}</h2>
                </a>
                <div class="caption">
                    {{ post.pub_date }}<br>

                    <img id="sda" src="{{MEDIA_URL}}{{post.photo_set.all.0.photo_file.url}}"
                         style="width:300px;height:200px;">

                    <form action="{% url 'whayp:delete_post' post.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{ post.id }}"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>

                    <a href="{% url 'whayp:favorite_post' post.id %}" class="btn btn-default btn-sm btn-favorite"
                       role="button">
                        <span class="glyphicon glyphicon-star {% if post.is_favorite %}active{% endif %}"></span>
                    </a>

                </div>
            </div>
        </div>
        <div class="clearfix visible-lg"></div>
        {% endfor %}
        {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{% url 'whayp:create_post' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Post
                </button>
            </a>
        </div>
        {% endif %}
    </div>

    <!-- If user searches and there are photos -->
    {% if photos %}
    <div class="row">
        <div class="col-sm-12">
            <h3>photos</h3>
        </div>
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>photo Title</th>
                            <th>Artist</th>
                            <th>Audio File</th>
                            <th>Post</th>
                            <th>Favorite</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for photo in photos %}
                        <tr>
                            <td>{{ photo.photo_title }}</td>
                            <td>{{ photo.post.artist }}</td>
                            <td>
                                <a target="_blank" href="{{ photo.audio_file.url }}">
                                    <button type="button" class="btn btn-success btn-xs">
                                        <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                    </button>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'whayp:detail' photo.post.id %}">
                                    <img src="{{ photo.post.post_logo.url }}" class="img-responsive"
                                         style="width: 20px; float: left; margin-right: 10px;"/>
                                </a>
                                <a href="{% url 'whayp:detail' photo.post.id %}">{{ photo.post.post_title }}</a>
                            </td>
                            <td>
                                <a href="{% url 'whayp:favorite' photo.id %}" class="btn-favorite"><span
                                        class="glyphicon glyphicon-star {% if photo.is_favorite %}active{% endif %}"></span></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}

whayp/templates/whayp/login.html
{% extends 'whayp/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'whayp:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'whayp:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

whayp/templates/whayp/photos.html
{% extends 'whayp/base.html' %}
{% block title %}All Photos{% endblock %}
{% block photos_active %}active{% endblock %}

{% block body %}
<div class="container-fluid photos-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"
                    {% if filter_by == 'all' %}
                        class="active"
                {% endif %}>
                <a href="{% url 'whayp:photos' 'all' %}">View All</a></li>
                <li role="presentation"
                    {% if filter_by == 'favorites' %}
                class="active"
                {% endif %}>
                <a href="{% url 'whayp:photos' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                            {% for photo in photo_list %}
                                <img src="{{photo.photo_file.url}}"  style="width:300px;height:200px;">
                            {% endfor %}
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

whayp/templates/whayp/register.html
{% extends 'whayp/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'whayp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'whayp:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}